name: Test and build Android App

on:
  push:
    branches:
      - develop

jobs:
  release-android:
    name: Build and release Android App
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Install Fastlane & screengrab
        run: cd android && gem install bundler && bundle install

      - name: Install packages
        run: yarn install

      - name: Create google-service file (Firebase)
        run: 'echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json'
        shell: bash
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Create google-account-service file (Google Play)
        run: 'echo "$GOOGLE_SERVICE_ACCOUNT_JSON" > android/api-google-service-account.json'
        shell: bash
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}

      - name: Create the keystore binary from hex dump
        run: 'echo "$KEYSTORE_HEX" | xxd -r - android/app/mmowars-upload-key.keystore'
        shell: bash
        env:
          KEYSTORE_HEX: ${{ secrets.KEYSTORE_HEX }}

      - name: Add password to gradle file
        run: 'sed -i "s/KEYSTORE_PASSWORD/$KEYSTORE_PASSWORD/" android/gradle.properties'
        shell: bash
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Build app with fastlane and sign it
        run: cd android && fastlane android build_release